services:
  db:
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_DISABLE_UPGRADE_BACKUP: 1
    container_name: acme_db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MARIADB_USER=${DB_USER}
        - MARIADB_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
